config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  get 'student/list'
  get 'student/new'
  post 'student/create'
  patch 'student/update'
  get 'student/show'
  get 'student/edit'
  get 'student/destroy'
  get 'grades/new'
  post 'grades/create'
  get 'grades/destroy'
  resources :student, :grades
  root to: 'home#index'
end

app/models/grade.rb
class Grade < ApplicationRecord
  belongs_to :student

  validates :grade_name, presence: true
  validates :grade_day_t, presence: true, numericality: { only_integer: true, less_than_or_equal_to: 31 }
  validates :grade_month_t, presence: true, numericality: { only_integer: true, less_than_or_equal_to: 12 }
  validates :grade_year_t, presence: true, numericality: { only_integer: true, less_than_or_equal_to: 2021 }
  validates :grade_value, presence: true, numericality: { only_integer: true}
end

app/controllers/grades_controller.rb
class GradesController < ApplicationController
  def new
    @student = Student.find(params[:id])
    @grade = Grade.new
    @grade.student_id = @student.id
  end

  def create
    @grade = Grade.new(grade_params)
    @student = Student.find(grade_params[:student_id])

    if @grade.valid?
      @grade.save
      redirect_to student_show_path(id: grade_params[:student_id]), notice: 'Grade saved!'
    else
      flash.now[:notice] = @grade.errors.full_messages
      render action: 'new'
    end
  end

  def destroy
    @grade = Grade.find(params[:id])
    redirect_to student_show_path(id: @grade.student_id), notice: 'Grade deleted!'
    @grade.destroy
  end

  def grade_params
    params.require(:grade)
          .permit(:grade_name,
                  :grade_year_t,
                  :grade_month_t,
                  :grade_day_t,
                  :grade_value,
                  :student_id)
  end
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/views/grades/new.erb
<!DOCTYPE html>
<html>

<head>
    <title>StaticAiBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https: //www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https: //www.w3schools.com/lib/w3-theme-indigo.css">
</head>
<style>
    body,
    h1,
    h2,
    h3,
    h4,
    h5 {
        font-family: "Poppins", sans-serif
    }

    body {
        font-size: 16px;
    }
</style>

<body>

    <div class="w3-sidebar w3-bar-block w3-card" style="margin-top:75px;width:25%;right:0;position:absolute;">
        <div class="w3-margin">
            <% flash.each do |type, msg| %>
            <% msg.each do |m| %>
            <p style=""><%= m %></p>
            <% end %>
            <% end %>

        </div>

    </div>

    <div class="w3-main" style="margin-top:115px;margin-left:40px;margin-right:40px;margin-bottom:40px">

        <h1><%= @student.first_name %> <%= @student.last_name %></h1>


        <h3>Add new Grade</h3>

        <!-- local: true breaks shit -->
        <%= form_for @grade, local: true, url: grades_create_path do |f| %>

        <%= f.hidden_field :student_id, :value => @student.id %>

        <p>
            <label>Grade Name</label>:
            <%= f.text_field :grade_name %>
        </p>
        <p>
            <label>Grading Date</label>:
            <%= f.text_field :grade_year_t, placeholder: "Year", :size=>"5" %>
            <%= f.text_field :grade_month_t, placeholder: "Month", :size=>"5" %>
            <%= f.text_field :grade_day_t, placeholder: "Day", :size=>"5" %>
        </p>
        <p>
            <label>Grade Value</label>:
            <%= f.text_field :grade_value %>
        </p>

        <div style="display:inline">
            <%= f.submit "Submit grade", class: 'w3-button w3-border' %>
            <% end %>

            <%= link_to student_list_path(:search => "", :id => ""), class: 'w3-button w3-border' do %>Back<% end %>
        </div>
    </div>
</body>

</html>