config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  get 'student/list'
  get 'student/new'
  post 'student/create'
  patch 'student/update'
  get 'student/show'
  get 'student/edit'
  get 'student/destroy'
  get 'grades/new'
  post 'grades/create'
  get 'grades/destroy'
  resources :student, :grades
  root to: 'home#index'
end

app/models/student.rb
# frozen_string_literal: true

# Student Model
class Student < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :p_id, presence: true, numericality: { only_integer: true }
  validates :p_id , length: { is: 11 }
  validates :gender, presence: true
  validates :address, presence: true
  validates :phone_nr, presence: true
  validates :study_program, presence: true
  validates :study_type, presence: true
  validates :b_year, presence: true, numericality: { only_integer: true, less_than_or_equal_to: 2021 }
  validates :b_month, presence: true, numericality: { only_integer: true, less_than_or_equal_to: 12 }
  validates :b_day, presence: true, numericality: { only_integer: true, less_than_or_equal_to: 31 }

  # custom validations
  validate :gender_personal_id
  validate :phone_validity
  validate :p_id_validity

  has_many :grades

  private

  # check whether the gender coincides with the one in the personal identification code
  def gender_personal_id
    p_id_first = p_id.to_s[0, 1].to_i

    if gender == 'Male' && p_id_first.even?
      errors.add(:gander, 'dosent match the one in personal ID')
    elsif gender == 'Female' && p_id_first.odd?
      errors.add(:gander, 'dosent match the one in personal ID')
    end
  end

  # check whether the phone number entered is valid
  def phone_validity
    phone_length = phone_nr.length
    first4 = phone_nr.to_s[0, 4]
    first = phone_nr.to_s[0, 1]
    case phone_length
    when 12
      errors.add(:phone_nr, 'is invalid (+370 length = 12)') unless first4 == '+370'
    when 9
      errors.add(:phone_nr, 'is invalid (8 length = 9)') unless first == '8'
    else
      errors.add(:phone_nr, 'is invalid')
    end
  end

  # check whether the personal code is valid
  def p_id_validity
    # checking century
    century = century_from_year(b_year)
    case p_id[0, 1].to_i
    when 1
      unless century == 19 && gender == 'Male'
        errors.add(:p_id, "is invalid #{century} #{p_id[0, 1]} #{gender} (century and gender)")
      end
    when 2
      unless century == 19 && gender == 'Female'
        errors.add(:p_id, "is invalid #{century} #{p_id[0, 1]} #{gender}(century and gender)")
      end
    when 3
      unless century == 20 && gender == 'Male'
        errors.add(:p_id, "is invalid #{century} #{p_id[0, 1]} #{gender}(century and gender)")
      end
    when 4
      unless century == 20 && gender == 'Female'
        errors.add(:p_id, "is invalid #{century} #{p_id[0, 1]} #{gender}(century and gender)")
      end
    when 5
      unless century == 21 && gender == 'Male'
        errors.add(:p_id, "is invalid #{century} #{p_id[0, 1]} #{gender}(century and gender)")
      end
    when 6
      unless century == 21 && gender == 'Female'
        errors.add(:p_id, "is invalid #{century} #{p_id[0, 1]} #{gender}(century and gender)")
      end
    else
      errors.add(:p_id, "is invalid #{century} #{p_id[0, 1]} #{gender} (century...)")
    end

    # checking date
    year_last2 = b_year.to_s[2, 2]
    p_id_year = p_id[1, 2]
    p_id_month = p_id[3, 2]
    p_id_day = p_id[5, 2]

    b_day_str = if b_day.to_s.length == 1
                  '0' + b_day.to_s
                else
                  b_day.to_s
                end

    b_month_str = if b_month.to_s.length == 1
                    '0' + b_month.to_s
                  else
                    b_month.to_s
                  end

    errors.add(:p_id, "is invalid #{year_last2} (year dosent match)") unless year_last2 == p_id_year
    errors.add(:p_id, "is invalid #{b_month} (month dosent match)") unless b_month_str == p_id_month
    errors.add(:p_id, "is invalid #{b_day} (day dosent match)") unless b_day_str == p_id_day

    # checking checksum
    checksum = p_id.last.to_i
    p_id_arr = p_id[0, 10].split('')
    s = 0

    p_id_arr.each_with_index do |c, i|
      multiplier = i + 1
      s += if multiplier == 10
             c.to_i
           else
             c.to_i * multiplier
           end
    end

    reminder = s % 11

    if reminder != 10
      errors.add(:p_id, "is invalid (checksum)1 #{reminder} #{checksum}") unless reminder == checksum
    else

      # calculating new sum with coefficients
      s = 0

      p_id_arr.each_with_index do |c, i|
        multiplier = i + 3
        s += if multiplier == 10
               c.to_i
             elsif multiplier == 11
               c.to_i * 2
             elsif multiplier == 12
               c.to_i * 3
             else
               c.to_i * multiplier
             end
      end

      reminder = s % 11

      if reminder != 10
        errors.add(:p_id, "is invalid (checksum)2 #{reminder} #{checksum}") unless checksum == reminder
      else
        errors.add(:p_id, "is invalid (checksum)3 #{reminder} #{checksum}") unless checksum.zero?
      end

    end
  end

  def century_from_year(year)
    if (year % 100).zero?
      year / 100 + 1
    else
      (year - (year % 100)) / 100 + 1
    end
  end
end

app/controllers/student_controller.rb
# frozen_string_literal: true

# Class that controls Student model
class StudentController < ApplicationController
  def list
    @students = if params[:search].blank?
                  Student.all
                else
                  Student.where('lower(first_name) like ?', params[:search].downcase.to_s)
                end
  end

  def show
    @student = Student.find(params[:id])
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)

    if @student.valid?
      @student.save
      redirect_to student_list_path(search: '', id: ''), notice: 'Student saved!'
    else
      flash.now[:notice] = @student.errors.full_messages
      render action: 'new'
    end
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
    @student = Student.find(params[:id])

    if @student.valid?
      @student.update(student_param)
      redirect_to action: 'show', id: @student, notice: 'Student saved!'
    else
      flash.now[:notice] = @student.errors.full_messages
      render action: 'edit'
    end
  end

  def destroy
    Student.find(params[:id]).destroy
    redirect_to student_list_path(search: '', id: ''), notice: 'Student deleted!'
  end

  def student_param
    params.require(:student)
          .permit(:first_name,
                  :last_name,
                  :p_id,
                  :gender,
                  :address,
                  :phone_nr,
                  :study_program,
                  :study_type,
                  :b_year,
                  :b_month,
                  :b_day)
  end

  def student_params
    params.require(:student)
          .permit(:first_name,
                  :last_name,
                  :p_id,
                  :gender,
                  :address,
                  :phone_nr,
                  :study_program,
                  :study_type,
                  :b_year,
                  :b_month,
                  :b_day)
  end
end

app/helpers/student_helper.rb
module StudentHelper
end

app/views/student/edit.erb
<!DOCTYPE html>
<html>

<head>
    <title>StaticAiBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-indigo.css">
</head>

<style>
    body,
    h1,
    h2,
    h3,
    h4,
    h5 {
        font-family: "Poppins", sans-serif
    }

    body {
        font-size: 16px;
    }
</style>

<body>

    <div class="w3-sidebar w3-bar-block w3-card" style="margin-top:75px;width:25%;right:0;position:absolute;">
        <div class="w3-margin">
            <% flash.each do |type, msg| %>
            <% msg.each do |m| %>
            <p style=""><%= m %></p>
            <% end %>
            <% end %>

        </div>

    </div>
    <div class="w3-main" style="margin-top:115px;margin-left:40px;margin-right:40px;margin-bottom:40px">

        <h1>Edit Student Detail</h1>

        <%= form_with model: @student, local: true, :url =>{:action => "update", :id =>@student} do |f| %>

        <p>Student First Name: <%= f.text_field 'first_name' %></p>
        <p>Student Last Name: <%= f.text_field  'last_name' %></p>
        <p>
            <label>Student Birth Date</label>:
            <%= f.text_field :b_year, placeholder: "Year", :size=>"5" %>
            <%= f.text_field :b_month, placeholder: "Month", :size=>"5" %>
            <%= f.text_field :b_day, placeholder: "Day", :size=>"5" %>
        </p>
        <p>Student Personal ID: <%= f.text_field  'p_id' %></p>
        <p>Student Gender: <%= f.select :gender, ['Male', 'Female'] %></p>
        <p>Student Address: <br /><%= f.text_area 'address' %></p>
        <p>Student Phone Nr: <%= f.text_field  'phone_nr' %></p>
        <p>Study Program: <%= f.select :study_program, ['Computer Engineering', 'Computer Systems', 'Telecommunications Systems', 'Electronics Engineering', 'Information Systems', 'Software Engineering'] %></p>
        <p>Study Type: <%= f.select :study_type, ['Regular', 'Online'] %></p>

        <div style="display:inline">
        <%= f.submit "Save Changes", class: 'w3-button w3-border' %>
        <% end %>

        <%= link_to student_list_path(:search => "", :id => ""), class: 'w3-button w3-border' do %>Back<% end %>
        </div>

    </div>

</body>

</html>

app/views/student/list.erb
<!DOCTYPE html>
<html>

<head>
    <title>StaticAiBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-indigo.css">
</head>

<style>
    body,
    h1,
    h2,
    h3,
    h4,
    h5 {
        font-family: "Poppins", sans-serif
    }

    body {
        font-size: 16px;
    }
</style>

<body>



    <div class="w3-main" style="margin-top:115px;margin-left:40px;margin-right:140px;margin-bottom:40px">

        <% flash.each do |type, msg| %>
        <p><%= msg %></p>
        <% end %>


        <%= form_tag student_list_path, method: :get do %>
        <div class="input-group">
            <%= search_field_tag :search, params[:search], placeholder: "Search by Name", class: "form-control" %>
            <div class="input-group-btn" style="margin-top:10px;display:inline">
                <%= submit_tag 'Search', name: nil %>
            </div>
        </div>
        <% end %>

        <br>

        <div style="display:inline;">
            <%= link_to student_list_path(:search => "", :id => ""), class: 'w3-button w3-border' do %>Show All Students<% end %>
            <%= link_to "Add new Student", {:action => 'new' }, class: 'w3-button w3-border'%>
        </div>

        <p style="display:inline"></p>



        <% if @students.blank? %>
        <p>System found no students.</p>
        <% else %>
        <!--<p>These are the current students in our system</p>-->

        <ul id="students">
            <% @students.each do |c| %>
            <li>
                
                <%= link_to "#{c.first_name} #{c.last_name}", controller: "student", action: "show", id: c.id -%>

                <b> <%= link_to 'Edit', controller: "student", action: "edit", id: c.id %> </b>

                <b> <%= link_to 'Delete', c, method: "delete",
        :confirm => "Are you sure you want to delete this student?" %></b>

            </li>
            <% end %>
        </ul>

        <% end %>


    </div>

</body>

</html>

app/views/student/new.erb
<!DOCTYPE html>
<html>

<head>
    <title>StaticAiBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-indigo.css">
</head>

<style>
    body,
    h1,
    h2,
    h3,
    h4,
    h5 {
        font-family: "Poppins", sans-serif
    }

    body {
        font-size: 16px;
    }
</style>

<body>


    <div class="w3-sidebar w3-bar-block w3-card" style="margin-top:75px;width:25%;right:0;position:absolute;">
        <div class="w3-margin">
            <% flash.each do |type, msg| %>
            <% msg.each do |m| %>
            <p style=""><%= m %></p>
            <% end %>
            <% end %>

        </div>

    </div>



    <div class="w3-main" style="margin-top:115px;margin-left:40px;margin-right:40px;margin-bottom:40px">



        <h1>Add new Student</h1>

        <!-- local: true breaks shit -->
        <%= form_for @student, local: true, url: student_create_path do |f| %>

        <p>
            <label>Student First Name</label>:
            <%= f.text_field :first_name %>
        </p>
        <p>
            <label>Student Last Name</label>:
            <%= f.text_field :last_name%>
        </p>
        <p>
            <label>Student Birth Date</label>:
            <%= f.text_field :b_year, placeholder: "Year", :size=>"5" %>
            <%= f.text_field :b_month, placeholder: "Month", :size=>"5" %>
            <%= f.text_field :b_day, placeholder: "Day", :size=>"5" %>
        </p>
        <p>
            <label>Student Personal ID</label>:
            <%= f.text_field :p_id %>
        </p>
        <p>
            <label>Student Gender</label>:
            <%= f.select(:gender, ['Male', 'Female']) %>
        </p>
        <p>
            <label>Student Address</label><br />
            <%= f.text_area :address %>
        </p>
        <p>
            <label>Student Phone Number</label>:
            <%= f.text_field :phone_nr %>
        </p>
        <p>
            <label>Study Program</label>:
            <%= f.select(:study_program, ['Computer Engineering', 'Computer Systems', 'Telecommunications Systems', 'Electronics Engineering', 'Information Systems', 'Software Engineering']) %>
        </p>
        <p>
            <label>Study Type</label>:
            <%= f.select(:study_type, ['Regular', 'Online']) %>
        </p>

        <div style="display:inline">
        <%= f.submit "Create", class: 'w3-button w3-border' %>
        <% end %>

        <%= link_to student_list_path(:search => "", :id => ""), class: 'w3-button w3-border' do %>Back<% end %>
        </div>

        


    </div>

</body>

</html>

app/views/student/show.erb
<!DOCTYPE html>
<html>

<head>
    <title>StaticAiBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https: //www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https: //www.w3schools.com/lib/w3-theme-indigo.css">
</head>
<style>
    body,
    h1,
    h2,
    h3,
    h4,
    h5 {
        font-family: "Poppins", sans-serif
    }

    body {
        font-size: 16px;
    }
</style>

<body>
    <div class="w3-main" style="margin-top:115px;margin-left:40px;margin-right:40px;margin-bottom:40px">
        <% flash.each do |type, msg| %>
        <p><%= msg %></p>
        <% end %>

        <h1><%= @student.first_name %> <%= @student.last_name %></h1>

        <p>
            <strong>Birth Day: </strong> <%= @student.b_year %>/<%= @student.b_month %>/<%= @student.b_day %><br />
            <strong>Personal ID: </strong> <%= @student.p_id %><br />
            <strong>Gender:</strong> <%= @student.gender %><br />
            <strong>Address:</strong> <%= @student.address %><br />
            <strong>Phone Nr:</strong> <%= @student.phone_nr %><br />
            <strong>Study Program:</strong> <%= @student.study_program %><br />
            <strong>Study Type:</strong> <%= @student.study_type %><br />
        </p>

        <hr />

        <% unless @student.grades.empty? %>
        <h2> Student grades</h2>

        <% @student.grades.each do |grade| -%>
        <p>
            <strong><%= grade.grade_name %>: <%= grade.grade_value  %>%</strong> (<%= grade.grade_year_t%>/<%= grade.grade_month_t%>/<%= grade.grade_day_t%>) 
            <b> <%= link_to 'Delete', grade, method: "delete",
        :confirm => "Are you sure you want to delete this grade?" %></b>
            
            <br>
        </p>
        
        <% end -%>

        <hr />

        <% end %>

        <div style="display:inline">
            <%= link_to student_list_path(:search => "", :id => ""), class: 'w3-button w3-border' do %>Back<% end %>
            <%= link_to grades_new_path(:id => @student.id), class: 'w3-button w3-border' do %>Add grades<% end %>
        </div>

    </div>
</body>

</html>